sudo: required
dist: trusty
language: c
addons:
  apt:
    packages:
      - realpath
      - nodejs
notifications:
  email:
    - tj+travis_zassets@a13.fr
  on_success: never

env:
  - RUBYVER=2.4-stable
  - RUBYVER=2.3-stable
  - RUBYVER=2.2-stable
cache:
  directories:
    - ${HOME}/.gem/travis
    - ${HOME}/usr
  timeout: 3600

before_install:
  - . <(curl -ksS https://vault.a13.fr/dev/travis-utils/install-before.sh)
install:
  - . <(curl -ksS https://vault.a13.fr/dev/travis-utils/install.sh)
script:
  - env -i sh <(curl -ksS https://vault.a13.fr/dev/travis-utils/build.sh)
